name: Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail ./**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
